### ISSUE TITLE
CASE_STATUS_CHANGE event not working in version 1.3.0

### ISSUE THREAD

**Issue by davewhitehouse** [nice-devone/nice-cxone-chat-web-sdk#7]
We have come across what appears to be an issue with the @nice-devone/nice-cxone-chat-web-sdk version 1.3.0.

When upgrading from 1.2.0 to 1.3.0 we have noticed that some event listeners are no longer receiving events.

One key Event for us is ChatEvent.CASE_STATUS_CHANGE. This event triggers as expected in version 1.2.0 and 1.0.0 but when updated to 1.3.0 of the SDK we no longer see this event exposed through the SDK. The event can be seen in the websocket data however so it is being sent from CXOne to the client.

**Comment by davewhitehouse** [comment]
looks like you have deprecated CASE_STATUS_CHANGED

    AUTHORIZE_CONSUMER = "AuthorizeConsumer",
    /** @deprecated use CONTACT_CREATED */
    CASE_CREATED = "CaseCreated",
    /** @deprecated use ASSIGNED_AGENT_CHANGED */
    CASE_INBOX_ASSIGNEE_CHANGED = "CaseInboxAssigneeChanged",
    /** @deprecated use CONTACT_STATUS_CHANGED */
    CASE_STATUS_CHANGED = "CaseStatusChanged",
    /** @deprecated use CONTACT_TO_ROUTING_QUEUE_ASSIGNMENT_CHANGED */
    CASE_TO_ROUTING_QUEUE_ASSIGNMENT_CHANGED = "CaseToRoutingQueueAssignmentChanged"

You really need to reflect this in the documentation here: https://help.nice-incontact.com/content/acd/digital/chatsdk/chatwebsdklibrary/variables/chatevent.htm

Also deprecated normally means the old method will work for a period of time and not just be turned off.

**Comment by enzy** [comment]
The `CASE_STATUS_CHANGED` was already deprecated in previous releases.

We need to provide a clearer changelog here to know about these BCs.

Thank you for your feedback.
